### ISSUE TITLE
名前を考える

### ISSUE THREAD

**Issue by Chaha1n** [Chaha1n/GenTwo-server#1]

**Comment by Chaha1n** [comment]
みんなアイデアを投げつけてください

**Comment by lemon-0451** [comment]
Gen
Next generation SNSが由来。俗説にはゲンちゃんが語源とも。

**Comment by kathmandu777** [comment]
mandu(マンドゥー):
Baidu(中国のgoogle)っぽい響きで良くない？知らんけど。

**Comment by tmtmNasubi** [comment]
GEN WORLD(ジェンワールド):
訳: やさしいせかい の Gentle world から

**Comment by Chaha1n** [comment]
> GEN WORLD(ジェンワールド):
> 訳: やさしいせかい の Gentle world から

ながい

**Comment by kathmandu777** [comment]
fluffy(フラッフィー)=軽くただよう

**Comment by lemon-0451** [comment]
> GEN WORLD(ジェンワールド):
> 訳: やさしいせかい の Gentle world から

Gentle要素とても良い

**Comment by Chaha1n** [comment]
GenならGentoo Penguinをマスコットにするのも良さそう

**Comment by tmtmNasubi** [comment]
> > GEN WORLD(ジェンワールド):
> > 訳: やさしいせかい の Gentle world から
> 
> ながい　けどよさげ

Gentld

**Comment by Chaha1n** [comment]
Gentoo
Genちゃん、Next Gen、Gentleで
Gentle too

**Comment by Chaha1n** [comment]
Gentoo、Twitter2→Gen2ともできるしやっぱりこれでは、とふとおもいました。
Gentle World/Generation Twoの略としてGentwoとするのもよさそう

**Comment by kathmandu777** [comment]
> Gentoo、Twitter2→Gen2ともできるしやっぱりこれでは、とふとおもいました。
> Gentle World/Generation Twoの略としてGentwoとするのもよさそう

`ペンギンの中では臆病で穏やかな性格。ジェンツーペンギンは「温順ペンギン」とよばれるほどおっとり穏やかな性格。`
らしいので、優しいtwitterという点もカバーできているし、俺は大賛成！

**Comment by lemon-0451** [comment]
> Gentle World/Generation Twoの略としてGentwoとするのもよさそう

造語いいね

**Comment by kathmandu777** [comment]
# 最終候補
1. Gentwo
2. Gen2
3. Gentoo

1,2は同じかも？他にもあれば追加して、今日中にきめちゃお。

**Comment by lemon-0451** [comment]
このissueをcloseしませんか？
